### ISSUE TITLE
Plugin randomly dies with a connection shutdown error message

### ISSUE THREAD

**Issue by jtlisi** [intelsdi-x/snap-plugin-collector-snmp#16]
`time="2016-12-13T19:31:31-05:00" level=error msg="collector run error" _module=scheduler-job block=run error="connection is shut down" job-type=collector`

**Snap daemon version** (use `snapteld -v`):
`snapteld version test-c2aef10`

**Environment**:
- snmp udp endpoint at port 161

**Task Config**:
```
      "config": {
        "/intel/snmp": {
          "snmp_agent_name": "*********",
          "snmp_agent_address": "*******:161",
          "snmp_version": "v2c",
          "community": "*******",
          "network": "udp",
          "timeout": 15,
          "retries": 0
        }
      }
```
I've tried numerous different timeouts and retry configurations and nothing seems to work. One thing that seems to cause is my setfile has snmp elements in the namespace. Also it will work for hours at a time and then suddenly drop. Once the error message is shown the plugin does not recover regardless of the max-failures.

**Comment by nanliu** [comment]
@jtlisi, please review https://github.com/intelsdi-x/snap/pull/1456, and see if the daemon control setting `max_plugin_restarts` to a high value resolve this. If you are able to try the latest build, you can set `max_plugin_restarts: -1` to disable this behavior. We also provided additional logging message to indicate the plugin has been disabled due to multiple failures:

```
level=warning msg="plugin disabled due to exceeding restart limit: 10"
```

A linux test build of the latest version of snap is available at:
https://s3-us-west-2.amazonaws.com/snap.ci.snap-telemetry.io/snap/latest/linux/x86_64/snapteld

**Comment by nanliu** [comment]
Based on other user's feedback and our test results, we believe this is fixed per comment above. If you still run into this issue, please feel free to reopen this issue.
